#!/bin/bash

# Save the original container PATH.
PATH_CONTAINER="$PATH"

# Source the user's profile if it exists.
[ -f "/tmp/container_env_runtime/user_profile" ] && source "/tmp/container_env_runtime/user_profile"

# Check if PATH_CONTAINER is a substring of PATH.
# If not concatenate PATH_CONTAINER and PATH so that the PATH setup by the
# container is preserved
if [[ ":$PATH:" != *":$PATH_CONTAINER:"* ]]; then
  export PATH="$PATH_CONTAINER:$PATH"
fi
